rimgid/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
import order, static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    ('^/?contact_form(/(?P<ex>[^/]+))?/?$', order.contact_form),
    
    # админка------------------:
    (r'^admin/', include(admin.site.urls)),
    
    # заказ экскурсии------------------:
    ('^/?order_excursion/(?P<ex>\w+)/(?P<mail>\w+)/(?P<text>\w+)/?$', order.excursion_order),
    
    # статика ------------------:
    ('^/?(?P<name>\w+).css/?$', static.get_css),
    ('^/?rimgid/wysiwyg/(?P<name>[^.]+)\.(?P<tp>\w+)/?$', static.get_from_wysiwyg),
    ('^/?(?P<name>\w+).js/?$', static.get_js),
    ('^/?(images/)?((?P<papka>\w+)/)?(?P<name>[^/]+)\.(?P<tp>\w+)/?$', static.get_image),
    ('^/?ds_stamper.ttf/?$', static.get_image, {'tp':'ttf'}),
)

rimgid/articles/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from rimgid.wysiwyg import WYSIWYGField
import datetime
from django.contrib.sites.models import Site
from django.contrib.flatpages.models import FlatPage
from django.utils.text import truncate_words
from django.utils.html import strip_tags
from rimgid.added.thumbs import ImageWithThumbsField
from django.db.models.signals import post_save
from rimcelery import tasks

def add_image_to_tasks(path):
    """
    Добавляет задание на копирование файла
    """
    tasks.duplicate_image.apply_async( [path] )
    print "TASK ADDED..."
        
class ArticleSpecial(models.Model):
    """
    Модель "Особенности статьи" - используется в модели Article
    """
    name = models.CharField(max_length = 200, blank = "True")
    text = WYSIWYGField(blank="True")
    image = models.ImageField(default=False, upload_to='images', null="True", blank='True')
    
    stype = "article"

    def __unicode__(self):
        try:
            atype = self.article_set.all()[0].atype.title
        except:
            atype = ""
        txt = strip_tags(self.text)
        txt = self.name + " ["+atype+"] = " + txt
        k = 50
        if len(txt) > k:
            txt = txt[:k-3] + "..."
        if self.image:
            txt += " img:" + str(self.image)
        return txt
        
# Добавляем задание на копирование файла из ArticleSpecial
def special_save_handler(sender, **kwargs):
    print "special_save_handler", kwargs['instance'].image
    add_image_to_tasks(str(kwargs['instance'].image))
    
# После сохранения ArticleSpecial будет выполнена special_save_handler
post_save.connect(special_save_handler, sender=ArticleSpecial)

class ArticleTypeSpecial(ArticleSpecial):
    """
    Модель "Особенности типа статьи" - используется в модели ArticleType
    """
    stype = "articleType"

class ArticleType(models.Model):
    """
    Модель "Тип статьи" - используется для определения способа вывода статьи и задания общих особенностей
    """
    title = models.CharField(max_length=200)
    text = WYSIWYGField(null="True", blank="True")
   
    def type_name_postfix(self):
        try:
            sp = self.specials.get(name="type_name_postfix")
            return sp.text
        except:
            return ""
            
    def title_with_postfix(self):
        return self.title + self.type_name_postfix()
    
    specials = models.ManyToManyField(ArticleTypeSpecial, null="True", blank="True")
    
    def __unicode__(self):
        try:
            sp = self.specials.get(name="name")
            try:
                sps = sp.text.split("|")
                return sps[settings.SITE_ID-1]
            except:
                return sp.text
        except:
            return self.title
   
class Foto(models.Model):
    """
    Модель "Фото" - используется в галерее фотографий (страница фото)
    """
    title = models.CharField(max_length=200)
    url = models.CharField(max_length=200)
    text = WYSIWYGField(blank="True")
    #---- HEAD
    image = ImageWithThumbsField(upload_to='images', sizes=((200,200),))    
    #image = models.ImageField(upload_to="fotos/",null="True", blank="True")
    #image = models.ImageField(upload_to="fotos/",null="True", blank="True")
    #----
    #image = ImageWithThumbsField(upload_to='images', sizes=((200,200),))    
    #image = models.ImageField(upload_to="fotos/",null="True", blank="True")
    ##image = models.ImageField(upload_to="fotos/",null="True", blank="True")
    #---- to here ...7b4ef1aded17b86
    datetime = models.DateTimeField(blank="True")
    sites = models.ManyToManyField(Site)

    def __unicode__(self):
        return self.title + " - " + self.image.url_200x200
        
# добавляем задание на копирование двух файлов из Foto
def foto_save_handler(sender, **kwargs):
    print "foto_save_handler"
    print kwargs['instance'].image, kwargs['instance'].image.url_200x200
    add_image_to_tasks(kwargs['instance'].image)
    add_image_to_tasks(kwargs['instance'].image.url_200x200)
    
# После сохранения Foto будет выполнена foto_save_handler
post_save.connect(foto_save_handler, sender=Foto)

class Article(FlatPage):
    """
    Основной класс "статья". Наполнение сайта полностью определяется
    добавлением и редактированием статей. Остальные модели используются
    для их настройки.
    """
    atype = models.ForeignKey(ArticleType)
    specials = models.ManyToManyField(ArticleSpecial, null="True", blank="True")
    datetime = models.DateTimeField(blank="True",default=datetime.datetime.now) #auto_now_add=True
        
    # узнаем заданную особенность 'image'
    def image(self):
        try:
            sp = self.specials.get(name='image')
            if sp.image:
                return str(sp.image)
            return sp.text
        except:
            return False
    
    # проверяем, что не нужно создавать свою страницу
    def is_only_in_list(self):
        try:
            sp = self.atype.specials.get(name='only_in_list')
        except:
            pass
        else:
            if sp.text == "True":
                return True
        return False
    
    def __init__(self, *args, **kwargs):
        """
        Берем особенности из выбранного типа статьи
        """
        super(Article, self).__init__( *args, **kwargs)
        if len(self.template_name)>0:
            return
        try:
            a_t = self.atype.specials.get(name='article_template')
        except:
            pass
        else:
            self.template_name = a_t.text
        try:
            a_t = self.atype.specials.get(name='article_title')
        except:
            pass
        else:
            self.title = a_t.text
            

rimgid/templatetags/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
from rimgid.wysiwyg import WYSIWYGField
from django.contrib.flatpages.models import FlatPage
from django.contrib.sites.models import Site
import datetime

class ProjectOption(models.Model):
    name = models.CharField(max_length=200)
    value = WYSIWYGField(blank="True")
    sites = models.ManyToManyField(Site)
    
    def get_sites(self):
        return '; '.join([s.name for s in self.sites.all()])
    
    def __unicode__(self):
        return self.name + " ["+str(self.get_sites())+"]" + " = " + self.value
        

rimgid/forms.py
# -*- coding: utf-8 -*-
from django import forms
import datetime
from templatetags.project_options import get_project_option

class ContactForm(forms.Form):
    #mp = get_main_params()
    request_msg_error = get_project_option('request_msg_error')
    request_title = get_project_option('request_title')
    msg_thx = get_project_option('msg_thx')
    name = forms.CharField(
      required = False,
      label = get_project_option('form_label_name'),
      widget = forms.TextInput(
        attrs = {
          'placeholder' : get_project_option('form_input_name'),
          'id' : 'order_name'
        },
      ),
    )
    subject = forms.CharField(
      required = False,
      label = get_project_option('form_label_date'),
      widget = forms.TextInput(
        attrs = {
          'placeholder' : get_project_option('form_input_date'),
          'id' : 'order_date'
        },
      ),
    )
    email = forms.EmailField(
      required = True,
      label = get_project_option('form_label_email'),
      widget = forms.TextInput(
        attrs = {
          'placeholder' : get_project_option('form_input_email'),
          'id' : 'order_mail'
        },
      ),
    )
    message = forms.CharField(
      required = False,
      label = get_project_option('form_label_comments'),
      widget = forms.Textarea(
        attrs = {
          'placeholder' : get_project_option('form_input_comments'),
          'id' : 'order_text'
        },
      ),
    )

rimgid/articles/templatetags/views.py
# -*- coding: utf-8 -*-
from django.template import Template, Context
from django.template.loader import get_template
from django.conf import settings
from rimgid.articles.models import Article, Foto
import settings

def articles_list(name,template="articles/articles_list.html",order_by='id'):
    """
    вывод списка статей по типу
    """
    try:
        sp = name.split("|")
        name = sp[0]
        template = sp[1]
    except:
        pass
    articles = Article.objects.filter(
                    atype__title__exact = name, #фильтруется по atype.title
                    sites__id__exact=settings.SITE_ID
                ).order_by(order_by)
                
    #print name, " count = ", str(len(articles))
                
    t = get_template(template)
    return t.render(Context({'articles': articles}))
    
def fotos_list(template="articles/fotos_view.html",order_by='id',url=""):
    """
    вывод фотографий
    """
    fotos = Foto.objects.filter(
                    sites__id__exact=settings.SITE_ID
                ).order_by(order_by)
    fotos
    t = get_template(template)
    ft_titles = [u'Фото','Photos'] #FIXME вшито использование SITE_ID
    ft_title = ft_titles[settings.SITE_ID-1]
    return t.render(Context({'fotos': fotos,'type_url': url, 'type_title': ft_title}))

rimgid/articles/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponse, HttpResponseRedirect, Http404
from django.template import Template, Context, loader, RequestContext
from django.template.loader import get_template
from django.shortcuts import render_to_response, get_object_or_404
from django.conf import settings
from django.contrib import auth
import datetime, random, os, time
from rimgid.articles.models import *
from django.core.xheaders import populate_xheaders
from django.utils.safestring import mark_safe
from django.views.decorators.csrf import csrf_protect
from django.contrib.flatpages.views import render_flatpage
from models import Article

DEFAULT_TEMPLATE = 'flatpages/default.html'

"""
def method_splitter(request, GET=None, POST=None):
    if request.method == 'GET' and GET is not None:
        return GET(request)
    elif request.method == 'POST' and POST is not None:
        return POST(request)
    raise Http404

def get_page(request, url='404'):
    pass
"""

def article(request, url):
    """
    метод используется для объекта Article вместо аналогичного для объекта FlatPage 
    """
    #if not url.endswith('/') and settings.APPEND_SLASH:
    #    return HttpResponseRedirect("%s/" % request.path)
    if url.startswith('http://'):
        return HttpResponseRedirect("%s" % request.path)
    
    if url.endswith('/') and len(url) > 1: #and settings.APPEND_SLASH:
        return HttpResponseRedirect("%s" % request.path[0:len(request.path)-1])
    if not url.startswith('/'):
        url = "/" + url
    #try:
    f = get_object_or_404(Article, url__exact=url, sites__id__exact=settings.SITE_ID)
    if f.is_only_in_list():
        raise Http404('No %s matches the given query.' % f.url)
    #except MultipleObjectsReturned:    
    return render_flatpage(request, f)
    
"""
def file_text(template):
    t = get_template(template)
    return t.render(Context({}))
"""

rimgid/templates/base_contacts.html
{% extends "base.html" %}

{% block style %}
  #content {
    width: 100%;
    margin: 10px 0px 10px 0px;
  }
  #content-down {
    width: 46%;
    position: relative;
    float: left;
    margin: 2%;
  }
  #content-up {
    background: #000033 url("rim-fon-3.jpg");
    width: 980px;
  }
  #body, html {
    background5: #009900;
  }
{% endblock %}

{% block content_up %}
    <div id="content-up" align="justify" style="margin-top=-10px;border='solid 10px #333';width=100%;">
      <div class="foto_with_podpis"><div style="background:url('olga.png');width:200px;height:220px;"></div><div class="podpis" style="top:220px;width:180px;width=200px;">Ольга Новикова - <span style="font-weight:normal;font-size:8pt;">русскоговорящий лицензированный гид-переводчик по Риму и региону Лацио</span></div></div>
      <h1 style="text-align: center;">Контакты</h1>
{% if contacts_list %}
  {% for contact in contacts_list %}
      <div class="rounded" style="margin:10px;float:left;width:210px;background:#000033;color:#fff;">
        <img src="{{ contact.image }}" height="50px" style="margin:5px;float:left;" />
        <h3 style="text-align:center;">{{ contact.name }}</h3>
        {{ contact.value }}
      </div>
  {% endfor %}
{% endif %}
    </div>
{% endblock %}

{% block content_down %}
    {% if note %}
      <div id="content-down" align="justify">  
        {% if note.image != '0' %}<img src="{{ note.image }}" width="150px" align="left" vspace="5" style="margin-top:24px;margin-right:10px;border='solid 1px #333';"/>{% endif %}
        <h1>{{ note.title }}</h1><div style="text-align:right;margin-top:-40px;float:right;right:0px;"><a href="/notes">Новости</a></div>
        {{ note.date }} - {{ note.text }}
      </div>
    {% endif %}
    {% if shop %}
      <div id="content-down" align="justify">  
        {% if shop.image != '0' %}<img src="{{ shop.image }}" width="150px" align="left" vspace="5" style="margin-top:24px;margin-right:10px;border='solid 1px #333';"/>{% endif %}
        <h1>{{ shop.title }}</h1><div style="text-align:right;margin-top:-40px;float:right;right:0px;"><a href="/shops">Магазины</a></div>
        {{ shop.text }}
      </div>
    {% endif %}
    {% if transport %}
      <div id="content-down" align="justify">  
        {% if transport.image != '0' %}<img src="{{ transport.image }}" width="150px" align="left" vspace="5" style="margin-top:24px;margin-right:10px;border='solid 1px #333';"/>{% endif %}
        <h1>{{ transport.title }}</h1><div style="text-align:right;margin-top:-40px;float:right;right:0px;"><a href="/transport">Транспорт</a></div>
        {{ transport.text }}
      </div>
    {% endif %}
{% endblock %}

rimgid/templates/base_main.html
{% extends "base_with_ex.html" %}

{% block content_up %}
<div id="content-up" align="justify" style="margin-top=-10px;border='solid 10px #333';">
  <div id="olga_info" style="margin-top:-15px;">
    <div class="foto_with_podpis"><div class="rounded_up" style="background:url('/olga.png');width:200px;height:220px;margin-top=10px;"></div><div class="podpis" style="width:180px;width=200px;">Ольга Новикова - <span style="font-weight:normal;font-size:8pt;">русскоговорящий лицензированный гид-переводчик по Риму и региону Лацио</span></div></div>
    {% if content_up %}<h1>content_up.title</h1>{{ content_up.text }}{% endif %}
    <h1 style="text-align: center;">Экскурсии в Риме</h1>
    <span style="font-weight:bold;">Предлагаю Вам увлекательные экскурсии по Риму</span> и его пригородам со мной - русскоговорящим лицензированным гидом-переводчиком по Риму и региону Лацио. Вы сможете посетить археологические музеи, соборы, картинные галереи, музеи скульптуры и многое другое. Так как Рим расположен близ западного побережья Центральной Италии (примерно в 20 километрах от места впадения реки Тибр в Тирренское море), мы также сможем совершить интересные поездки на живописные морские курорты.
    <div style="margin:10;">
      <div style="float:left;"><a class="light" href="/guida_turistica.pdf"><img src="/pdf.png" width="36"/> Лицензия</a></div>
      <div style="float:left;margin:10;">
        <a class="light" href="/italy">- Экскурсии по другим городам Италии</a><br>
        <a class="light" href="/translate">- Услуги перевода</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block content_down %}
{% if note %}
<div id="content-down" align="justify">
  {% if note.image != "0" %}
  <img src="{{ note.image }}" width="150px" align="left" vspace="5" style="margin-top:24px;margin-right:10px;border='solid 1px #333;'"/>
  {% endif %}
  <h1>{{ note.title }}</h1><div class="note_place"><a href="/notes">Новости</a></div>
  {{ note.date }} - {{ note.text }}
</div>
{% endif %}
{% if shop %}
<div id="content-down" align="justify">
  {% if shop.image != "0" %}
  <img src="{{ shop.image }}" width="150px" align="left" vspace="5" style="margin-top:24px;margin-right:10px;border='solid 1px #333;'"/>
  {% endif %}
  <h1>{{ shop.title }}</h1><div class="note_place"><a href="/shops">Магазины</a></div>
  {{ shop.text }}
</div>
{% endif %}
{% if transport %}
<div id="content-down" align="justify">
  {% if transport.image != "0" %}
  <img src="{{ transport.image }}" width="150px" align="left" vspace="5" style="margin-top:24px;margin-right:10px;border='solid 1px #333;'" />
  {% endif %}
  <h1>{{ transport.title }}</h1><div class="note_place"><a href="/transport">Транспорт</a></div>
  {{ transport.text }}
</div>
{% endif %}
  {% if excursion_list %}
  {% for excursion in excursion_list %}
  {% endfor %}
  {% endif %}
{% endblock %}

rimgid/templates/contact_form.html
<html>
<head>
    <title>Contact us</title>
    <style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
    #order_form {width:480px;padding:0px;margin:0px;}
    #order_form h2 {padding:5px;margin:5px;}
    #order_name {width:460px;border-radius:4px;border:1px solid #363636;margin:5px;padding:5px;}
    #order_mail {width:460px;border-radius:4px;border:1px solid #363636;margin:5px;padding:5px;}
    #order_date {width:460px;border-radius:4px;border:1px solid #363636;margin:5px;padding:5px;}
    #order_text {width:460px;border-radius:4px;border:1px solid #363636;margin:5px;padding:5px;}
    </style>
</head>
<body>
    {% if order_ok %}
       {{ form.msg_thx }}
    {% else %}
    <form id="order_form" action="" method="post">
        <h2>{{ form.request_title }}</h2>

        {% if form.errors %}
            <p style="color: red;">
                {{ form.request_msg_error }}
            </p>
        {% endif %}

            {% if form.name.errors %}
                <ul>
                {% for error in form.name.errors %}
                    <li><strong>{{ error }}</strong></li>
                {% endfor %}
                </ul>
            {% endif %}
            <label for="id_name">{{ form.name.label }}</label>
            {{ form.name }}

        <!--div id="order_date" class="field{% if form.subject.errors %} errors{% endif %}"-->
            {% if form.subject.errors %}
                <ul>
                {% for error in form.subject.errors %}
                    <li><strong>{{ error }}</strong></li>
                {% endfor %}
                </ul>
            {% endif %}
            <label for="id_subject">{{ form.subject.label }}</label>
            {{ form.subject }}
        <!--/div-->
        <!--div id="order_mail" class="field{% if form.email.errors %} errors{% endif %}"-->
            {% if form.email.errors %}
                <ul>
                {% for error in form.email.errors %}
                    <li><strong>{{ error }}</strong></li>
                {% endfor %}
                </ul>
            {% endif %}
            <label for="id_email">{{ form.email.label }}</label>
            {{ form.email }}
        <!--/div-->
        <!--div id="order_text" class="field{% if form.message.errors %} errors{% endif %}"-->
          {% if form.message.errors %}
              <ul>
              {% for error in form.message.errors %}
                  <li><strong>{{ error }}</strong></li>
              {% endfor %}
              </ul>
          {% endif %}
          <label for="id_message">{{ form.message.label }}:</label>
          {{ form.message }}
        <!--/div-->
        <input type="submit" id="ordersubmit" value="OK" />
    </form>
  {% endif %}

    <!--form id="orderform" method="post" action="" onsubmit="return orderExcursion('{{ excursion.title }}',mail.text,comment.text);">
      {% csrf_token %}
      <p id="orderform_result">vfdv</p>
      <div>Для заказа этой экскурсии введите свой адрес электронной почты. На этот адрес я вышлю ответ.</div>
      <input type="text" placeholder="адрес почты..." size="35" maxlength="50" name="mail" id="mail" /> 
      <input type="text" placeholder="дата..."  size="35" maxlength="50" name="phone" id="phone" /> 
      <textarea id="comment"  placeholder="комментарий к заказу..."></textarea>
      <input type="submit" id="ordersubmit" value="Заказать" />
    </form-->

</body>
</html>

rimgid/templates/ttt.html
<!--DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd"-->
<!--html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"-->
<html>
  <head>
    <title>{{ page.title }}</title>
    <meta NAME="KeyWords" CONTENT="{{ page.keywords }}">
    <meta NAME="Description" CONTENT="{{ page.description }}">
    <meta http-equiv="Content-Language" content="ru">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <!--meta content=document name=resourse-type><link href="/style.css" rel="stylesheet" type="text/css"-->
    <style>
      body,html {margin:0;padding:0;background:#363636;min-width:1200px;width:100%;color:#fff;}
      #main {width:1200px;left:50%;margin-left:-600px;float:left;position:relative;background:#555;}
      #header {width:100%;float:left;text-align:center;}
      #base {width:100%;background:#000077;float:left;}
      #content {width:70%;background:#777;float:left;}
      #right {width:30%;background:#999;float:left;}
      #footer {width:100%;float:left;}
      .green {
        background-color:#007700;background:-moz-linear-gradient(top, #007700, #009900);
        background:-webkit-gradient(linear, left top, left bottom, from(#007700), to(#009900));
        filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0, startColorstr=#007700, endColorstr=#009900);}
      .dgreen {
        background-color:#009900;background:-moz-linear-gradient(top, #009900, #007700);
        background:-webkit-gradient(linear, left top, left bottom, from(#009900), to(#007700));
        filter:progid:DXImageTransform.Microsoft.gradient(GradientType=0, startColorstr=#009900, endColorstr=#007700);}
      .rgreen {
        background-color:#009900;background:-moz-linear-gradient(left, #009900, #007700);
        background:-webkit-gradient(linear, top left, bottom left, from(#009900), to(#007700));
        filter:progid:DXImageTransform.Microsoft.gradient(GradientType=1, startColorstr=#009900, endColorstr=#007700);}
      ul.mainmenu {
        width:460px;height:50px;padding-left:20px;margin:0;margin-right:20px;
        list-style:none;position:relative;border-radius:10px 10px 0 0;
        font-weight:bold;background3:#00f0ff url('2.png');
        float:right;clear:right;
      }
      ul.mainmenu li {float:left;}
      ul.mainmenu li a, ul.mainmenu li a:visited {
        width:100px;height:50px;padding:5px;margin-right:1px;
        color:#fff;text-align:center;text-decoration:none;vertical-align:middle;
        display:table-cell;
      }
      ul.mainmenu_2 li a, ul.mainmenu_2 li a:visited {
        width:100px;padding:5px;margin-right:1px;display:block;
        color:#999999;text-align:center;text-decoration:none;
      }
      ul.mainmenu li a:hover {
        border-radius: 10px;
        -moz-border-radius: 10px;
        -webkit-border-radius: 10px;
        color: #99ff99;
        background-color: #00bb00;
        background: -moz-linear-gradient(top, #00bb00, #009900);
        background: -webkit-gradient(linear, left top, left bottom, from(#00bb00), to(#009900));
        filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0, startColorstr=#00bb00, endColorstr=#009900);
      }
      ul.mainmenu_2 li a:hover {
        border-radius:10px;-moz-border-radius:10px;-webkit-border-radius:10px;
        color: #999;
        background-color: #eee;
        background: -moz-linear-gradient(top, #eee, #fff);
        background: -webkit-gradient(linear, left top, left bottom, from(#eee), to(#fff));
        filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0, startColorstr=#eee, endColorstr=#fff);
        margin-top: -8px;
        height: 24px;
      }
      #left_p {width:10px;height:100%;margin-left:-10px;position:absolute;}
      #right_p {width:10px;height:100%;margin-right:-10px;position:absolute;right:0px;}
    </style>
  </head>
  <body>
    <div id="main">
      <div id="header" class="green">
        <h1>{{ site.title }}</h1>
        <ul class="mainmenu green">
          <li><a href="">1</a></li>
          <li><a href="">2</a></li>
          <li><a href="">3</a></li>
        </ul>
      </div>
      <div id="base">
        <div id="content">{{ page.content }}</div>
        <div id="right">{{ site.right }}</div>
      </div>
      <div id="footer" class="dgreen">{{ site.footer }}</div>
      <div id="left_p" class="lgreen"></div>
      <div id="right_p" class="rgreen"></div>
    </div>
  </body>
</html>